import Head from "next/head";
import Image from "next/image";
import { useState, useRef } from "react";

export default function Home() {
  const [menu, setMenu] = useState(false);
  const hamburger = useRef(null);
  const showMenu = (e) => {
    if (menu === false) {
      hamburger.current.classList.toggle("active");
      setMenu(true);
    } else {
      hamburger.current.classList.remove("active");
      setMenu(false);
    }
  };

  return (
    <div>
      <Head>
        <title>champagne</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-[100%] bg-black/50 fixed" style={{display: menu === true? 'block' : 'none'}}></div>
      <div className="w-[400px] h-full bg-black pl-5 pt-16 fixed z-[10]" style={{display: menu === true? 'block' : 'none'}}>
        <h1 className="text-white text-[20px] mb-1">Home</h1>
        <h1 className="text-white text-[20px] mb-1">Invest</h1>
        <h1 className="text-white text-[20px] mb-1">Trade</h1>
        <h1 className="text-white text-[20px] mb-1">Build</h1>

        <h1 className="text-white text-[16px] mt-8 text-gray-400">Products</h1>
        <h1 className="text-white text-[18px]">Invest app</h1>
        <h1 className="text-white text-[18px]">Trade app</h1>
        <h1 className="text-white text-[18px]">Claim $BAL</h1>

        <h1 className="text-white text-[16px] mt-8 text-gray-400">Learn</h1>
        <h1 className="text-white text-[18px]">Blog</h1>
        <h1 className="text-white text-[18px]">Documentation</h1>
        <h1 className="text-white text-[18px]">Whitepaper</h1>
        <h1 className="text-white text-[18px]">Careers</h1>

        <h1 className="text-white text-[16px] mt-8 text-gray-400">Ecosystem</h1>
        <h1 className="text-white text-[18px]">Snapshot government</h1>
        <h1 className="text-white text-[18px]">Dune analytics</h1>
        <h1 className="text-white text-[18px]">Forum</h1>
        <h1 className="text-white text-[18px]">Grants</h1>

        <div className="flex mt-8">
          <svg
            data-v-4c469572=""
            id="twitter"
            width="32"
            height="32"
            xmlns="http://www.w3.org/2000/svg"
            aria-labelledby="logoTitle"
            role="img"
            className="logo-group"
          >
            <title data-v-4c469572="" id="twitterTitle">
              Link to Balancer&apos;s Twitter
            </title>{" "}
            <g data-v-4c469572="" fillRule="nonzero" fill="none">
              <path
                data-v-4c469572=""
                d="M15.962 0C7.147 0 0 7.164 0 16s7.147 16 15.962 16 15.963-7.164 15.963-16S24.777 0 15.962 0z"
                fill="#FFF"
                className="bg"
              ></path>{" "}
              <path
                data-v-4c469572=""
                d="M24.031 12.86c.244 5.387-3.764 11.392-10.86 11.392-2.157 0-4.164-.635-5.855-1.721a7.673 7.673 0 005.656-1.586 3.83 3.83 0 01-3.57-2.66c.6.115 1.19.082 1.726-.065-1.837-.37-3.106-2.03-3.064-3.804a3.805 3.805 0 001.73.479A3.84 3.84 0 018.612 9.78a10.836 10.836 0 007.874 4.002c-.557-2.395 1.256-4.703 3.724-4.703 1.097 0 2.09.465 2.788 1.21a7.61 7.61 0 002.426-.93 3.844 3.844 0 01-1.68 2.119 7.608 7.608 0 002.193-.604 7.679 7.679 0 01-1.906 1.985z"
                fill="#000"
                className="logo"
              ></path>
            </g>
          </svg>
          <svg
            data-v-ea960c88=""
            id="discord"
            width="32"
            height="32"
            xmlns="http://www.w3.org/2000/svg"
            aria-labelledby="discordTitle"
            role="img"
            className="logo-group ml-2"
          >
            <title data-v-ea960c88="" id="discordTitle">
              Link to Balancer&apos;s Discord
            </title>{" "}
            <g data-v-ea960c88="" fill="none" fillRule="evenodd">
              <path
                data-v-ea960c88=""
                d="M15.981 0C7.167 0 .02 7.163.02 16c0 8.836 7.148 16 15.962 16 8.815 0 15.962-7.164 15.962-16 0-8.837-7.147-16-15.962-16z"
                fill="#FFF"
                className="bg"
              ></path>{" "}
              <path
                data-v-ea960c88=""
                d="M20.302 24.464l-.494-1.727L21 23.848l1.127 1.045 2.002 1.774V9.923A1.916 1.916 0 0022.219 8H9.744a1.916 1.916 0 00-1.91 1.923V22.54c0 1.064.857 1.923 1.91 1.923h10.559zm-1.676-4.275l-.615-.756c1.22-.345 1.685-1.11 1.685-1.11-.381.252-.745.429-1.07.55a6.118 6.118 0 01-1.35.402 6.508 6.508 0 01-2.412-.01 7.802 7.802 0 01-1.369-.401 5.45 5.45 0 01-.68-.317l-.037-.022-.01-.004-.037-.021-.037-.028-.26-.159s.446.747 1.629 1.102l-.624.774c-2.058-.065-2.84-1.418-2.84-1.418 0-3.006 1.341-5.442 1.341-5.442 1.34-1.008 2.617-.98 2.617-.98l.093.112c-1.676.486-2.45 1.223-2.45 1.223l.55-.27c.996-.44 1.788-.56 2.114-.589l.158-.018a7.577 7.577 0 014.684.877s-.736-.7-2.319-1.185l.13-.15s1.276-.028 2.617.98c0 0 1.34 2.436 1.34 5.442 0 0-.761 1.302-2.848 1.418zm-.932-4.358c-.53 0-.95.466-.95 1.036 0 .569.429 1.036.95 1.036.531 0 .95-.467.95-1.036 0-.57-.419-1.036-.95-1.036zm-3.398 0c-.531 0-.95.466-.95 1.036 0 .569.428 1.036.95 1.036.53 0 .95-.467.95-1.036.009-.57-.42-1.036-.95-1.036z"
                fill="#000"
                className="logo"
              ></path>
            </g>
          </svg>
          <svg
            data-v-4bc8ba2b=""
            id="medium"
            width="32"
            height="32"
            xmlns="http://www.w3.org/2000/svg"
            aria-labelledby="mediumTitle"
            role="img"
            className="logo-group ml-2"
          >
            <title data-v-4bc8ba2b="" id="mediumTitle">
              Link to Balancer&apos;s blog on Medium
            </title>{" "}
            <g data-v-4bc8ba2b="" fill="none" fillRule="evenodd">
              <g data-v-4bc8ba2b="" fillRule="nonzero">
                <path
                  data-v-4bc8ba2b=""
                  d="M16 0C7.185 0 .038 7.164.038 16S7.185 32 16 32s15.962-7.164 15.962-16S24.815 0 16 0z"
                  fill="#FFF"
                  className="bg"
                ></path>{" "}
                <path
                  data-v-4bc8ba2b=""
                  d="M11.826 10.4c2.984 0 5.403 2.507 5.403 5.6 0 3.093-2.419 5.6-5.403 5.6-2.984 0-5.403-2.507-5.403-5.6 0-3.094 2.419-5.6 5.403-5.6zm8.624.328c1.492 0 2.702 2.361 2.702 5.272s-1.21 5.271-2.702 5.271-2.702-2.36-2.702-5.271c0-2.91 1.21-5.272 2.702-5.272zm4.17.549c.526 0 .95 2.115.95 4.723 0 2.608-.425 4.723-.95 4.723-.524 0-.95-2.115-.95-4.723 0-2.608.426-4.723.95-4.723z"
                  fill="#000"
                  className="logo"
                ></path>
              </g>
            </g>
          </svg>
          <svg
            data-v-17fddb46=""
            id="github"
            width="32"
            height="32"
            xmlns="http://www.w3.org/2000/svg"
            aria-labelledby="githubTitle"
            role="img"
            className="logo-group ml-2"
          >
            <title data-v-17fddb46="" id="githubTitle">
              Link to Balancer Lab&apos;s Github
            </title>{" "}
            <g data-v-17fddb46="" fill="none">
              <path
                data-v-17fddb46=""
                d="M16.019 0C7.204 0 .057 7.164.057 16s7.147 16 15.962 16S31.98 24.836 31.98 16 24.834 0 16.02 0z"
                fill="#FFF"
                className="bg"
              ></path>{" "}
              <path
                data-v-17fddb46=""
                d="M18.97 24.821c-.472.092-.623-.198-.623-.448v-2.561c0-.87-.305-1.439-.64-1.728 2.075-.23 4.254-1.02 4.254-4.605 0-1.02-.363-1.852-.96-2.506.097-.236.416-1.185-.091-2.47 0 0-.78-.251-2.558.956a9.024 9.024 0 00-2.333-.312 8.95 8.95 0 00-2.332.313c-1.778-1.207-2.56-.956-2.56-.956-.505 1.285-.187 2.235-.09 2.47a3.614 3.614 0 00-.96 2.505c0 3.576 2.173 4.376 4.242 4.612-.266.233-.507.644-.59 1.248-.533.238-1.88.65-2.71-.776 0 0-.492-.896-1.428-.963 0 0-.908-.012-.063.568 0 0 .611.287 1.033 1.365 0 0 .539 1.667 3.13 1.102v1.737c0 .247-.15.536-.615.45a9.332 9.332 0 01-6.368-8.855c0-5.156 4.17-9.334 9.31-9.334 5.142 0 9.312 4.178 9.312 9.334a9.332 9.332 0 01-6.36 8.854z"
                fill="#000"
                className="logo"
              ></path>
            </g>
          </svg>
          <svg
            data-v-6104ed00=""
            id="linkedin"
            width="32"
            height="32"
            xmlns="http://www.w3.org/2000/svg"
            aria-labelledby="linkedinTitle"
            role="img"
            className="logo-group ml-2"
          >
            <title data-v-6104ed00="" id="linkedinTitle">
              Link to Balancer&apos;s LinkedIn profile
            </title>{" "}
            <g data-v-6104ed00="" fillRule="nonzero" fill="none">
              <path
                data-v-6104ed00=""
                d="M16 0C7.163 0 0 7.164 0 16s7.163 16 16 16c8.836 0 16-7.163 16-16 0-8.836-7.164-16-16-16z"
                className="bg"
              ></path>{" "}
              <path
                data-v-6104ed00=""
                d="M11.307 23.059H7.622V11.943h3.685V23.06zM9.464 10.425h-.023c-1.237 0-2.037-.854-2.037-1.92 0-1.09.824-1.92 2.085-1.92 1.26 0 2.037.83 2.06 1.92 0 1.066-.8 1.92-2.085 1.92zM24.596 23.06H20.91V17.11c0-1.493-.533-2.513-1.868-2.513-1.017 0-1.623.687-1.89 1.351-.097.238-.121.57-.121.902v6.208h-3.685s.048-10.073 0-11.116h3.685v1.574c.489-.756 1.365-1.835 3.32-1.835 2.426 0 4.244 1.589 4.244 5.003v6.374z"
                className="logo"
              ></path>
            </g>
          </svg>
          <svg
            data-v-2daca3a2=""
            id="mail"
            width="32"
            height="32"
            xmlns="http://www.w3.org/2000/svg"
            aria-labelledby="mailTitle"
            role="img"
            className="logo-group"
          >
            <title data-v-2daca3a2="" id="mailTitle">
              Link to Balancer Lab&apos;s contact email address
            </title>{" "}
            <g data-v-2daca3a2="" fillRule="nonzero" fill="none">
              <path
                data-v-2daca3a2=""
                d="M16.038 0C7.223 0 .075 7.164.075 16s7.148 16 15.963 16S32 24.836 32 16 24.853 0 16.038 0z"
                className="bg"
              ></path>{" "}
              <path
                data-v-2daca3a2=""
                d="M7.347 11.612l8.69 7.06 8.691-7.06v10.584H7.348V11.612zm17.369-1.86l-8.678 7.05-8.68-7.05h17.358z"
                className="logo"
              ></path>
            </g>
          </svg>
        </div>
      </div>
      <div className="bg-gradient-to-r from-black to-indigo-800">
        <div className="flex flex-row justify-between p-4 fixed w-full z-[9]">
          <div className="flex flex-row items-center">
            <div className="flex justify-center items-center">
              <div>
                <Image
                  src="/assets/logo.png"
                  alt="Vercel Logo"
                  width={40}
                  height={40}
                />
              </div>
              <h4 className="mx-1 text-white font-['NexaTextBold']">ChampagneSwap</h4>
            </div>
            <div className="flex text-white ml-4 font-['NexaTextBold'] lg:flex hidden">
              <h6 className="mx-2 text-sm">Swap</h6>
              <h6 className="mx-2 text-sm">Trade</h6>
              <h6 className="mx-2 text-sm">Pools</h6>
              <h6 className="mx-2 text-sm">Lend</h6>
              <h6 className="mx-2 text-sm">Borrow</h6>
            </div>
          </div>
          <div className="flex items-center">
            <div className="flex font-['NexaTextBold']">
              <div className="flex text-white mx-2 hidden md:flex">
                <h5 className="text-sm">Blog</h5>
                <div className="-mt-1 ml-1">
                  <Image
                    src="/assets/Vector.png"
                    alt="Vector"
                    width={8}
                    height={8}
                  />
                </div>
              </div>
              <div className="flex text-white mx-2 hidden md:flex">
                <h5 className="text-sm">Docs</h5>
                <div className="-mt-1 ml-1">
                  <Image
                    src="/assets/Vector.png"
                    alt="Vector"
                    width={8}
                    height={8}
                  />
                </div>
              </div>
              <div className="flex text-white mx-2 hidden md:flex">
                <h5 className="text-sm">Analytics</h5>
                <div className="-mt-1 ml-1">
                  <Image
                    src="/assets/Vector.png"
                    alt="Vector"
                    width={8}
                    height={8}
                  />
                </div>
              </div>
            </div>
            <div className="ml-4 hidden md:block">
              <button className="bg-[#10D281] px-4 py-1 text-sm rounded-lg font-['NexaTextBlack']">
                Enter App
              </button>
            </div>
            <div className="ml-4 z-[50]">
              <div className="inline-block mt-1 hamburger" ref={hamburger} onClick={showMenu}>
                <div className="w-[25px] h-[2px] bg-white my-2 bar1"></div>
                <div className="w-[25px] h-[2px] bg-white my-2 bar2"></div>
                <div className="w-[25px] h-[2px] bg-white my-2 bar3"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-center items-center text-white pt-20">
          <div>
            <Image
              src="/assets/logo_big.png"
              alt="Vercel Logo"
              width={175}
              height={175}
            />
          </div>
          <h1 className="text-5xl font-['NexaTextBold'] mt-5 text-center">
            Automated <span className="font-gradient font-['NexaTextHeavy']">DeFi</span> made simple
          </h1>
          <h1 className="mt-6 font-['NexaTextLight'] text-center">
            Light-speed <span className="font-['NexaTextBold']">Swaps</span>,
            Next-level
            <span className="font-['NexaTextBold']"> Liquidity</span>.
            Friction-less
            <span className="font-['NexaTextBold']"> yield farming.</span>
          </h1>
          <h1 className="text-center">
            Next-generation
            <span className="font-['NexaTextBold']">Borrowing</span> and{" "}
            <span className="font-['NexaTextBold']">Staking</span>.
          </h1>
          <div className="flex mt-6">
            <button className="bg-[#10D281] px-6 py-1.5 rounded-lg text-black font-['NexaTextBlack'] mx-2">
              Enter App
            </button>
            <button className="bg-[#202231] px-6 py-1.5 rounded-lg font-['NexaTextBlack'] mx-2">
              Learn More
            </button>
          </div>
        </div>
        <div className="flex mt-16 w-full flex-wrap justify-center">
          <div className="flex justify-between py-8 px-4 mt-0.5 items-center w-full sm:w-1/2 md:w-1/3 xl:w-1/5 border-r-black border-r-2 bg-[#10D281]">
            <h1 className="mx-2 font-['NexaTextBold'] text-sm">$CHAM Price</h1>
            <h1 className="text-4xl font-['NexaTextBlack'] mx-2">$0.43</h1>
          </div>
          <div className="flex justify-between py-8 px-4 mt-0.5 items-center w-full sm:w-1/2 md:w-1/3 xl:w-1/5 border-r-black border-r-2 bg-[#10D281]">
            <h1 className="mx-2 font-['NexaTextBold'] text-sm">
              Total Liquidity
            </h1>
            <h1 className="text-4xl font-['NexaTextBlack'] mx-2">$150M</h1>
          </div>
          <div className="flex justify-between py-8 px-4 mt-0.5 items-center w-full sm:w-1/2 md:w-1/3 xl:w-1/5 border-r-black border-r-2 bg-[#10D281]">
            <h1 className="mx-2 font-['NexaTextBold'] text-sm">Total Volume</h1>
            <h1 className="text-4xl font-['NexaTextBlack'] mx-2">$16.92B</h1>
          </div>
          <div className="flex justify-between py-8 px-4 mt-0.5 items-center w-full sm:w-1/2 md:w-1/2 xl:w-1/5 border-r-black border-r-2 bg-[#10D281]">
            <h1 className="mx-2 font-['NexaTextBold'] text-sm">Total Pairs</h1>
            <h1 className="text-4xl font-['NexaTextBlack'] mx-2">2,635</h1>
          </div>
          <div className="flex justify-between py-8 px-4 mt-0.5 items-center w-full md:w-1/2 xl:w-1/5 bg-[#10D281]">
            <div className="font-['NexaTextBold'] text-sm">
              <h1 className="mx-2">Supported</h1>
              <h1 className="mx-2">Blockchains</h1>
            </div>
            <h1 className="text-4xl font-['NexaTextBlack'] mx-2">14</h1>
          </div>
        </div>
      </div>
      <div className="bg-[#0D0415]">
        <div className="pt-16">
          <h1 className="text-2xl text-center text-white font-['NexaTextLight']">
            Celebrate your victories with earnings and
          </h1>
          <h1 className="text-2xl text-center text-white font-['NexaTextLight']">
            start <span className="font-['NexaTextBlack']">staking</span> and{" "}
            <span className="font-['NexaTextBlack']">spraying</span> with{" "}
            <span className="font-['NexaTextBlack']">Champagne</span>
          </h1>
        </div>
        <div className="flex justify-center mt-20 flex-wrap">
          <div className="flex w-[300px] h-[250px] relative m-2 px-8 pt-8 items-center flex-col bg-[#202231] rounded-lg">
            <h1 className="text-white font-['NexaTextBold']">
              Multi-chain AMM
            </h1>
            <h1 className="text-white text-sm mt-2 text-center font-['NexaTextLight']">
              The lowest rates for DeFi tokens anywhere. Switch to any
              blockchains in one click.
            </h1>
            <button className="bg-[#10D281] absolute bottom-0 mb-2 mt-4 py-2 px-3 rounded-lg text-black font-['NexaTextBlack'] mx-2">
              Enter Exchange
            </button>
          </div>
          <div className="flex w-[300px] h-[250px] relative m-2 px-8 pt-8 items-center flex-col bg-[#202231] rounded-lg">
            <h1 className="text-white font-['NexaTextBold'] text-center">
              Grape Lending &amp; Leverage
            </h1>
            <h1 className="text-white text-sm mt-2 text-center font-['NexaTextLight']">
              Isolated lending markets, elastic interest rates,Leverage long
              short or create your own market.
            </h1>
            <button className="bg-[#10D281] absolute bottom-0 mb-2 mt-4 py-2 px-3 rounded-lg text-black font-['NexaTextBlack'] mx-2">
              Enter Grape
            </button>
          </div>
          <div className="flex w-[300px] h-[250px] relative m-2 px-8 pt-8 items-center flex-col bg-[#202231] rounded-lg">
            <h1 className="text-white font-['NexaTextBold']">Cellar dApps</h1>
            <h1 className="text-white text-sm mt-2 text-center font-['NexaTextLight']">
              An innovative ecosystem to use dapps gas-efficiently and gain
              extra yield. Onchain min dapps.
            </h1>
            <button className="bg-[#10D281] absolute bottom-0 mb-2 mt-4 py-2 px-3 rounded-lg text-black font-['NexaTextBlack'] mx-2">
              Enter Cellar
            </button>
          </div>
          <div className="flex w-[300px] h-[250px] relative m-2 px-8 pt-8 items-center flex-col bg-[#202231] rounded-lg">
            <h1 className="text-white font-['NexaTextBold']">
              Cristal staking
            </h1>
            <h1 className="text-white text-sm mt-2 text-center font-['NexaTextLight']">
              Earn government rights and 0.05% of all swaps from all chains in
              one simple place.
            </h1>
            <button className="bg-[#10D281] absolute bottom-0 mb-2 mt-4 py-2 px-3 rounded-lg text-black font-['NexaTextBlack'] mx-2">
              Enter Cellar
            </button>
          </div>
          <div className="flex w-[300px] h-[250px] relative m-2 px-8 pt-8 items-center flex-col bg-[#202231] rounded-lg">
            <h1 className="text-white font-['NexaTextBold']">
              Champagne Program
            </h1>
            <h1 className="text-white text-sm mt-2 text-center font-['NexaTextLight']">
              Earn Champagne Bottles, once ChampagneSwap reached a marketcap on
              the coin of 1 Billion, it will create the worlds first DeFi
              Champagne in Champagne(France)
            </h1>
            <button className="bg-[#10D281] absolute bottom-0 mb-2 mt-4 py-2 px-3 rounded-lg text-black font-['NexaTextBlack'] mx-2">
              Coming Soon
            </button>
          </div>
        </div>
        <div className="text-white mt-32">
          <h1 className="text-3xl text-center font-['NexaTextBold']">
            An evolving community for an evolving
          </h1>
          <h1 className="text-3xl text-center font-['NexaTextBold']">
            <span className="font-['NexaTextBlack']">DeFi</span> landscape.
          </h1>
        </div>
        <div className="mt-16 flex justify-center flex-wrap">
          <div className="flex flex-col items-center w-[260px] h-[250px] py-8 bg-[#202231] m-2 rounded-lg">
            <div>
              <Image
                src="/assets/wallet.png"
                alt="wallet"
                width={120}
                height={120}
              />
            </div>
            <h1 className="text-white font-['NexaTextBlack'] text-center text-3xl">
              20+
            </h1>
            <h1 className="text-white font-['NexaTextLight'] text-sm mt-2 text-center">
              Wallet Supported
            </h1>
          </div>
          <div className="flex flex-col items-center w-[260px] h-[250px] pt-8 bg-[#202231] m-2 rounded-lg">
            <div>
              <Image
                src="/assets/blockchain.png"
                alt="wallet"
                width={120}
                height={120}
              />
            </div>
            <h1 className="text-white font-['NexaTextBlack'] text-center text-3xl">
              14
            </h1>
            <h1 className="text-white font-['NexaTextLight'] text-sm mt-2 text-center">
              Chains Supported
            </h1>
            <h1 className="text-white font-['NexaTextLight'] text-sm text-center">
              (BSC is first)
            </h1>
          </div>
          <div className="flex flex-col items-center w-[260px] h-[250px] py-8 bg-[#202231] m-2 rounded-lg">
            <div>
              <Image
                src="/assets/discord.png"
                alt="wallet"
                width={120}
                height={120}
              />
            </div>
            <h1 className="text-white font-['NexaTextBlack'] text-center text-3xl">
              10k+
            </h1>
            <h1 className="text-white font-['NexaTextLight'] text-sm mt-2 text-center">
              Discord Members
            </h1>
          </div>
          <div className="flex flex-col items-center w-[260px] h-[250px] py-8 bg-[#202231] m-2 rounded-lg">
            <div>
              <Image
                src="/assets/logo3.png"
                alt="wallet"
                width={120}
                height={120}
              />
            </div>
            <h1 className="text-white font-['NexaTextBlack'] text-center text-3xl">
              10k+
            </h1>
            <h1 className="text-white font-['NexaTextLight'] text-sm mt-2 text-center">
              Champagne Holders
            </h1>
          </div>
        </div>
        <div className="text-white mt-20">
          <h1 className="text-3xl text-center font-['NexaTextBold']">
            Make money on your{" "}
            <span className="font-['NexaTextBlack']">Crypto</span> with
          </h1>
          <h1 className="text-3xl text-center font-['NexaTextBold']">
            <span className="font-['NexaTextBlack']">ChampagneSwap</span> and{" "}
            <span className="font-['NexaTextBlack']">Celebrate</span>
          </h1>
        </div>
        <div className="flex flex-col items-center justify-center">
          <div className="w-full">
            <div className="mt-20 flex justify-center flex-col md:flex-row items-center px-2">
              <div className="flex flex-col items-center w-full mx-2 mt-2 md:w-[500px] py-5 bg-fuchsia-800 rounded-lg">
                <h1 className="text-5xl font-['NexaTextBlack'] text-center mt-4">
                  Earn
                </h1>
                <h1 className="text-5xl font-bold text-center mt-8">
                  <span className="font-['NexaTextBlack']">0.25%</span>
                </h1>
                <h1 className="font-['NexaTextBold'] text-center">Per Trade</h1>
                <button className="bg-black text-white rounded-md font-bold text-sm mt-8 mb-4 py-2 px-5">
                  Add Liquidity
                </button>
              </div>
              <div className="flex flex-col items-center w-full mx-2 mt-2 md:w-[500px] py-5 bg-[#10D281] rounded-lg">
                <h1 className="text-5xl font-['NexaTextBlack'] text-center mt-4">
                  Gain
                </h1>
                <h1 className="text-5xl font-bold text-center mt-8">
                  <span className="font-['NexaTextBlack']">0.05%</span>
                </h1>
                <h1 className="font-['NexaTextBlack'] text-center">
                  Per Trade in Cristal Coins
                </h1>
                <button className="bg-black text-white rounded-md font-bold text-sm mt-8 mb-4 py-2 px-5">
                  Add Liquidity
                </button>
              </div>
            </div>
          </div>
          <div className="w-full max-w-[1050px] px-2 md:px-4">
            <div className="mt-4 bg-cover bg-[url('/assets/Rectangle4.png')] rounded-[12px] flex flex-col sm:flex-row px-16 py-16 justify-between items-center">
              <h1 className="text-4xl w-full sm:w-1/4 font-['NexaTextBlack'] leading-normal">
                Learn how to DeFi?
              </h1>
              <div className="ml-0 sm:ml-6 w-full sm:w-3/4">
                <h1 className="font-['NexaTextBold']">
                  Check our guides to learn how to do Swap, add Liquidity,
                  install a Wallet to start trading. Learn how to Borrow Crypto
                  and make offering your crypto safely in the eco-system.
                </h1>
                <button className="bg-black text-white rounded-md font-['NexaTextBold'] text-sm mt-5 py-2 px-5">
                  START LEARNING
                </button>
              </div>
            </div>
            <img src="/assets/Rectangle5_1.png" className="w-full -mt-0.5" />
          </div>
        </div>
      </div>
      <footer className="bg-[#161522] py-20 flex justify-center hidden sm:flex">
        <div className="flex flex-col mx-6">
          <div className="flex items-center">
            <div>
              <Image
                src="/assets/logo.png"
                alt="Vercel Logo"
                width={40}
                height={40}
              />
            </div>
            <h1 className="mx-2 text-white">ChampagneSwap</h1>
          </div>
          <h1 className="text-white font-['NexaTextLight'] mt-3">
            ChampagneSwap is the home of DeFi.
          </h1>
          <h1 className="text-white font-['NexaTextLight']">
            Our community is the foremost
          </h1>
          <h1 className="text-white font-['NexaTextLight']">
            technologically beneficial platform for the
          </h1>
          <h1 className="text-white font-['NexaTextLight']">future of DeFi!</h1>
          <h1 className="text-white font-['NexaTextLight']">Join us!</h1>
          <div className="mt-4 flex">
            <div className="flex items-center">
              <Image
                src="/assets/Vector4.png"
                alt="Vector4"
                width={24}
                height={24}
              />
            </div>
            <div className="flex items-center ml-6">
              <Image
                src="/assets/Vector1.png"
                alt="Vector(1)"
                width={20}
                height={20}
              />
            </div>
            <div className="flex items-center ml-6">
              <Image
                src="/assets/Vector2.png"
                alt="Vector(1)"
                width={20}
                height={20}
              />
            </div>
          </div>
        </div>
        <div className="flex flex-col mx-6">
          <h1 className="text-white mt-2">PRODUCTS</h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">
            ChampagneSwap AMM
          </h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">
            Cellar Dapps
          </h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">
            Grape Lending
          </h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">
            API(Coming Soon)
          </h1>
        </div>
        <div className="flex flex-col mx-6">
          <h1 className="text-white mt-2">SUPPORT</h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">Tutorials</h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">
            Documentation
          </h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">Discord</h1>
        </div>
        <div className="flex flex-col mx-6">
          <h1 className="text-white mt-2">PROTOCOL</h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">Vote</h1>
          <h1 className="text-white font-['NexaTextLight'] mt-4">
            Create a Pair
          </h1>
        </div>
      </footer>
    </div>
  );
}
